name: Build and Deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    strategy:
      matrix:
        folder:
          - multilingual_motr/zh/

    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@v1.1
        id: versions
        with:
          path: ${{matrix.folder}}
          fallbackNode: '^12'
          fallbackNpm: '^6'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install and Build 🔧
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          cd ${{matrix.folder}}
          npm install
          npm run build

      - name: Configure git
        run: |
          git config --global user.email "cui.ding@uzh.ch"
          git config --global user.name "Cui Ding"

      - name: Remove existing worktree for gh-pages
        run: |
          if git worktree list | grep -q 'gh-pages'; then
            git worktree remove gh-pages --force
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create branch if it doesn't exist
        run: |
          git fetch origin
          if ! git rev-parse --verify origin/gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
          else
            git checkout gh-pages
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ${{ matrix.folder }}/dist
          target-folder: ${{ matrix.folder }}
          token: ${{ secrets.GITHUB_TOKEN }}